server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#sprin-config 에서 가져온다.
#app:
#  token:
#    access:
#      secret: qzXxcu0eMmiTljmLeiikLY3L2ULGDwbLbNMsvT/oEJ0lr3GGEtx4zVygOwZB94yM+HxmsTYyt09xe8WsxSUf1A==
#    refresh:
#      secret: ckoQEuWYg3fjSDsb30HPDK9xcTFogHpHkpgj7EBofs+/Ig5Y3CZ6I9gEKK1wcacDolQtukXFcAFJulWvRvCLdA==

spring:
  application:
    name: Api-Gateway-Service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      label: main # branch
      profile: default # profile
      #name: ecommerce # ecommerce.yaml 가져옴
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: API Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/test-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Logging Filter
                preLogger: true
                postLogger: true
#            - AddRequestHeader=test-request, test-request-header
#            - AddResponseHeader=test-response, test-response-header
#        login user-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
#        join user-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
#       actuator 내용도 jwt filter 를 타도록 변경하기 위해 주석 처리한다.
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/actuator/**
#            - Method=GET,POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - StripPrefix=1
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # 주의 API - GATEWAY 는 같은 path 에 경우 순서에 영향이 있음!
        # 같은 Path 인 경우 디테일 -> 간단 순으로 작성해야함
        # 만약 간단 -> 디테일이 되면 필터는 간단만 탈 수 있음.
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
            - JwtAuthorizationFilter
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoint:
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        #        refresh 사용하면 config 내용을 다시 불러온다, 현재 properties 내용이 val 이라서 변동할 수 없어 보인다. 수정 필요
        include: refresh, health, beans, httptrace, busrefresh