server:
  port: 0

spring:
  application:
    name: User-Service
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/userservice
#    username: userservice
#    password: userservice1234!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update #create validate update
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      label: main # branch
      profile: default # profile - default - 설정하지 않으면, spring-profiles-active 내용을 쓴다.
      #name: ecommerce # ecommerce.yaml 가져옴
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
#        refresh 사용하면 config 내용을 다시 불러온다, 현재 properties 내용이 val 이라서 변동할 수 없어 보인다. 수정 필요
        include: refresh, health, beans, busrefresh

app:
  message: E-Commerce User Service
  allowIp: 172.30.1.26
#  token:
#    access:
#      expiration_hour: 1 # a hour
#      secret: qzXxcu0eMmiTljmLeiikLY3L2ULGDwbLbNMsvT/oEJ0lr3GGEtx4zVygOwZB94yM+HxmsTYyt09xe8WsxSUf1A==
#    refresh:
#      expiration_hour: 24 # a day
#      secret: ckoQEuWYg3fjSDsb30HPDK9xcTFogHpHkpgj7EBofs+/Ig5Y3CZ6I9gEKK1wcacDolQtukXFcAFJulWvRvCLdA==

logging:
  level:
    com.pjhdev.UserService.client: DEBUG