server:
#  Random Port 사용
  port: 8081 #0

spring:
  application:
    name: TestService

eureka:
  # Port 를 랜덤 포트 사용하게 될 경우 Eureka 는 port 0으로 하나만 display 됨으로 instance 이름을 지정해준다.
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka